export {
  loadApi,
  setCurrentCurrency,
  loadCurrencyPage,
  toggleModal,
  changeUnit,
  searchUnits,
  getRates,
  changeCurrentRate,
  saveUnits,
  addCurrency,
  getCryptoes,
  addCurrencyBtnAction,
  changeUnitBtnAction,
} from './crypto';
